# ---------- SCENARIO 1: DEPLOY WITH REMOTE IMAGES ----------

#version: '3'
#services:
#  rs_server_webapp:
#    image: miccighel/rs_server:v1.0.11-alpha
#    command: rails server -p 3000 -b '0.0.0.0' -e production
#    ports:
#    - "3000:3000"
#    links:
#    - rs_server_database
#    container_name: webapp
#  rs_server_database:
#    image: postgres:10.5
#    ports:
#    - "5432"
#    container_name: postgres

# ---------- END OF SCENARIO 1: DEPLOY WITH REMOTE IMAGES ----------

# ---------- SCENARIO 2: DEPLOY WITH LOCAL BUILD ----------

version: '3'
services:
  rs_server_webapp:
    build: .
    image: miccighel/rs_server:v1.0.11-alpha
    command: rails server -p 3000 -b '0.0.0.0' -e production
    volumes:
    - .:/app
    ports:
    - "3000:3000"
    links:
    - rs_server_database
    container_name: webapp
  rs_server_database:
    image: postgres:11.1
    ports:
    - "5432"
    container_name: postgres

# ---------- END OF SCENARIO 2: DEPLOY WITH LOCAL BUILD ----------

# ---------- ADDITIONAL USEFUL COMMANDS ----------

# docker-compose run rs_server_webapp rake db:create
# docker-compose run rs_server_webapp rake db:migrate
# docker-compose run rs_server_webapp rake db:seed (Eventually)
# docker-compose run rails server -p 3000 -b '0.0.0.0' (Dev Mode)
# docker-compose run rails server -p 3000 -b '0.0.0.0' -e production (Prod Mode)

# ---------- END ----------