production:

development:
  # PATH NZXT
  #rs_pdf: M:\Dropbox\Documenti\Progetti\R@SM\R@SM-ReadersourcingServerSide\lib\PDFxReadersourcing-1.0-SNAPSHOT-jar-with-dependencies.jar
  #PATH SANTECH C37
  rs_pdf: E:\Dropbox\Documenti\Progetti\R@SM\R@SM-ReadersourcingServerSide\lib\PDFxReadersourcing-1.0-SNAPSHOT-jar-with-dependencies.jar
  rs_pdf_link_suffix: "-Link"

test: