development:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: admin
  password: puyes46r
  host: 127.0.0.1
  database: rs_server

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>