development:
  adapter: postgresql
  url: postgres://<%= ENV['POSTGRES_USER'] %>:<%= ENV['POSTGRES_PASSWORD'] %>@postgres/<%= ENV['POSTGRES_DB'] %>

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>