Default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: development
  user: postgres

test:
  <<: *default
  database: myapp_test

production:
  url: <%= ENV['DATABASE_URL'] %>